### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by peacememories** [daniloraisi/bs-react-bootstrap#1]
Hi, and thanks for creating this library :)

I've just started delving into ReasonML and ReasonReact, and the first thing I tried to do was start creating a bootstrap app. It seems that this library has been without a commit for quite some time. Is it still in active development? Are PRs welcome? I would like to have something like react-bootstrap@1.0.0 which supports bootstrap 4. I'm willing to give porting a few of the elements a shot, but as a caveat I just started with ReasonML and have no ocaml experience, so I don't know what my code quality will be.

**Comment by gigincg** [comment]
Hey @peacememories 
 What's your status on ReactBootstrap Bindings, If you've made some progress I'd love to add to it. This Repo seems like it's no longer supported, we could start a new repo and collaborate

**Comment by gigincg** [comment]
I've tried reaching @daniloraisi via Twitter. If he responds, maybe he could help us to collaborate in this project itself.

**Comment by daniloraisi** [comment]
As I talked with @gigincg, I'll open this repo within a org so you can contribute.
